import { esc, number, compact, duration, date, relative, serialize, statusClass, uiText } from './core.js';
import { icon } from './icons.js';

export const badge = status => `<span class="badge ${statusClass(status)}"><span class="dot"></span>${esc(status || 'Unknown')}</span>`;
export const button = (label, action, glyph = '', extra = '', klass = '') => `<button class="button ${klass}" data-action="${esc(action)}" ${extra}>${glyph ? icon(glyph) : ''}${esc(label)}</button>`;
export const heading = (title, subtitle, actions = '', eyebrow = 'WORKSPACE') => `<div class="page-heading"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div><div class="heading-actions">${actions}</div></div>`;
export const panelHeading = (title, sub = '', right = '') => `<div class="panel-heading"><div><h2>${title}</h2>${sub ? `<p>${sub}</p>` : ''}</div>${right}</div>`;
export const empty = (glyph, title, description, action = '') => `<div class="empty-state"><div class="empty-icon">${icon(glyph)}</div><h3>${esc(title)}</h3><p>${esc(description)}</p>${action}</div>`;
export const stat = (label, value, glyph, note, accent = '') => `<article class="stat-card ${accent}"><div class="stat-top"><span>${esc(label)}</span>${icon(glyph)}</div><div class="stat-value">${esc(value)}</div><div class="stat-note">${note}</div></article>`;
export function progress(task) {
  const steps = Number(task.steps) || 0, max = Number(task.config?.max_steps) || 0;
  const pct = max ? Math.min(100, steps / max * 100) : Math.min(100, Math.max(0, Number(task.progress) || 0));
  return `<div class="progress-meta"><span>Step budget</span><span class="mono">${number(steps)}${max ? ` / ${number(max)}` : ''} · ${number(pct)}%</span></div><div class="progress-track"><span style="width:${pct}%"></span></div>`;
}
export function taskTable(tasks, { small = false } = {}) {
  if (!tasks.length) return empty('tasks', 'Ready for your first task', 'Assign a task to an agent and track every action from this panel.', button('Assign task', 'assign', 'plus', '', 'secondary'));
  return `<div class="table-wrap"><table><thead><tr><th>TASK</th><th>AGENT</th><th>STATUS</th><th>${small ? 'ACTIVITY' : 'START / END'}</th>${small ? '' : '<th>DURATION</th><th>STEPS / TOKENS</th>'}<th></th></tr></thead><tbody>${tasks.map(task => `<tr><td><a class="table-title" href="#/tasks/${esc(task.id)}">${esc(task.prompt)}</a><span class="table-sub mono">${esc(task.id.slice(0, 12))}</span></td><td><a class="table-agent" href="#/agents/${esc(task.agent_id)}"><span class="avatar avatar-small">${icon('agents')}</span>${esc(task.agent_name || task.agent_id.slice(0, 8))}</a></td><td>${badge(task.status)}</td><td class="nowrap muted">${small ? relative(task.finished_at || task.started_at || task.created_at) : `${date(task.started_at)}<span class="table-sub">${date(task.finished_at)}</span>`}</td>${small ? '' : `<td class="mono nowrap">${duration(task.duration_seconds)}</td><td class="mono">${number(task.steps)}<span class="table-sub">${compact(task.total_tokens)} tokens</span></td>`}<td><a class="icon-button" href="#/tasks/${esc(task.id)}" aria-label="View task">${icon('chevron')}</a></td></tr>`).join('')}</tbody></table></div>`;
}
export function agentCard(agent) {
  return `<article class="agent-card"><div class="agent-card-top"><a class="avatar" href="#/agents/${esc(agent.id)}" aria-label="Open ${esc(agent.name)}">${icon('agents')}</a>${badge(agent.status)}</div><a class="agent-name" href="#/agents/${esc(agent.id)}">${esc(agent.name)}</a><p class="agent-description">${esc(agent.description || agent.role || 'General-purpose local agent')}</p><div class="model-tag">${icon('cpu')}<span>${esc(agent.config.model)}</span></div><div class="agent-current">${icon(agent.current_task ? 'activity' : 'clock')}<span>${esc(agent.current_task?.prompt || (agent.enabled ? 'Waiting for a task' : 'Agent disabled'))}</span></div><div class="agent-numbers"><span><strong>${number(agent.task_count)}</strong>Tasks</span><span><strong>${number(agent.success_rate)}%</strong>Success</span><span><strong>${compact(agent.total_tokens)}</strong>Tokens</span></div><div class="agent-card-bottom"><span class="muted small">${relative(agent.last_activity)}</span><a href="#/agents/${esc(agent.id)}">View agent ${icon('arrow')}</a></div></article>`;
}
export function chart(history = [], key = 'tasks', large = false) {
  const points = history.slice(-7), labels = { tasks: 'Tasks', tokens: 'Tokens', errors: 'Errors', duration_seconds: 'Duration (s)' };
  if (!points.length) return empty('metrics', 'No history available', 'History will appear when runs are recorded.');
  const vals = points.map(point => Number(point[key]) || 0), max = Math.max(4, ...vals) * 1.15, width = 680, height = large ? 240 : 192, top = 16, bottom = height - 30, left = 40, right = width - 12;
  const xy = vals.map((value, index) => [left + index * (right - left) / Math.max(1, vals.length - 1), bottom - value / max * (bottom - top)]);
  const line = xy.map((p, index) => `${index ? 'L' : 'M'}${p.join(',')}`).join(' '), fill = `${line} L${right},${bottom} L${left},${bottom} Z`;
  const total = vals.reduce((a, b) => a + b, 0), id = `chart-${key}`;
  return `<div class="chart-summary"><strong>${compact(total)}</strong><span>${esc(labels[key])} over the last 7 days</span><span class="chart-legend"><i></i>${esc(labels[key])}</span></div><svg class="history-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(labels[key])} per day: ${esc(points.map((p, i) => `${p.date}: ${vals[i]}`).join(', '))}"><defs><linearGradient id="${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#73d5b2" stop-opacity="0.2"/><stop offset="100%" stop-color="#73d5b2" stop-opacity="0.015"/></linearGradient></defs>${[0, .5, 1].map(n => { const y = bottom - n * (bottom - top); return `<line x1="${left}" x2="${right}" y1="${y}" y2="${y}" stroke="#232a35" stroke-dasharray="3 5"/><text x="0" y="${y + 4}" fill="#758090" font-size="10">${compact(max * n)}</text>`; }).join('')}<path d="${fill}" fill="url(#${id})"/><path d="${line}" fill="none" stroke="#73d5b2" stroke-width="2"/>${xy.map((p, i) => `<circle cx="${p[0]}" cy="${p[1]}" r="3" fill="#0f141b" stroke="#73d5b2" stroke-width="1.8"><title>${esc(points[i].date)}: ${number(vals[i])}</title></circle>`).join('')}${points.map((p, i) => `<text x="${xy[i][0]}" y="${height - 6}" text-anchor="${i === 0 ? 'start' : i === points.length - 1 ? 'end' : 'middle'}" fill="#7d8796" font-size="10">${new Date(`${p.date}T12:00:00Z`).toLocaleDateString('en-US', { day: '2-digit', month: 'short', timeZone: 'UTC' })}</text>`).join('')}</svg>`;
}
export function barChart(entries, key = 'calls', nameKey = 'name') {
  if (!entries.length) return empty('metrics', 'No activity yet', 'Runs will populate this chart.');
  const max = Math.max(1, ...entries.map(e => Number(e[key]) || 0));
  return `<div class="bar-chart">${entries.slice(0, 12).map(item => `<div class="bar-item"><div><span class="mono">${esc(item[nameKey])}</span><strong>${number(item[key])}</strong></div><div class="bar-track"><span style="width:${Math.max(0, Number(item[key]) || 0) / max * 100}%"></span></div></div>`).join('')}</div>`;
}
export function timeline(events = []) {
  if (!events.length) return empty('activity', 'Waiting for the first event', 'Run actions, results, and operational explanations will appear here.');
  return `<div class="timeline">${events.map((event, index) => `<article class="timeline-event ${statusClass(event.status)}"><div class="timeline-marker">${icon(event.error ? 'alert' : event.tool ? 'tool' : event.event_type?.includes('model') ? 'cpu' : 'activity')}</div><div class="timeline-content"><div class="timeline-top"><div><span class="timeline-step mono">${event.step_number ? `STEP ${number(event.step_number)}` : 'EVENT'}</span><strong>${esc(event.tool || event.event_type?.replaceAll('_', ' ') || 'Update')}</strong></div>${badge(event.status || event.level)}</div><div class="timeline-meta"><span>${date(event.timestamp)}</span>${event.duration_seconds != null ? `<span>${icon('clock')}${duration(event.duration_seconds)}</span>` : ''}${event.attempt ? `<span>Attempt ${number(event.attempt)}</span>` : ''}</div>${event.reason ? `<p class="reason">${esc(uiText(event.reason))}</p>` : ''}${event.error ? `<p class="event-error">${esc(uiText(event.error))}</p>` : ''}${[['Input', event.input], ['Output', event.output]].filter(([, value]) => value != null && value !== '').map(([label, value]) => `<details data-detail="event-${event.id || index}-${label}"><summary>${label} ${icon('chevron')}</summary><pre>${esc(serialize(value))}</pre></details>`).join('')}</div></article>`).join('')}</div>`;
}
export function logTable(events = []) {
  if (!events.length) return empty('logs', 'No events match these filters', 'Every action is logged automatically. Try different filters or run a task.');
  return `<div class="log-list">${events.map(event => `<details class="log-row" data-detail="log-${event.id}"><summary aria-label="${esc(`${date(event.timestamp)} · ${event.level} · ${event.event_type}${event.tool ? ` · ${event.tool}` : ''} · task ${event.task_id?.slice(0, 8) || '—'}`)}"><span class="log-time mono">${date(event.timestamp)}</span><span class="log-level ${event.level === 'ERROR' || event.level === 'CRITICAL' ? 'error' : event.level === 'WARNING' ? 'waiting' : ''}">${esc(event.level)}</span><span class="log-event"><span>${esc(event.event_type || 'Event')}</span>${event.tool ? `<code>${esc(event.tool)}</code>` : ''}</span><span class="log-task mono">${esc(event.task_id?.slice(0, 8) || '—')}</span>${icon('chevron')}</summary><div class="log-detail"><div class="key-values"><span>Agent</span><a href="#/agents/${esc(event.agent_id)}">${esc(event.agent_id || '—')}</a><span>Task</span><a href="#/tasks/${esc(event.task_id)}">${esc(event.task_id || '—')}</a><span>Step</span><span>${esc(event.step_id || '—')}</span><span>Status · duration · attempt</span><span>${esc(event.status || '—')} · ${duration(event.duration_seconds)} · ${number(event.attempt)}</span></div>${event.reason ? `<p class="log-reason">${esc(uiText(event.reason))}</p>` : ''}${event.error ? `<p class="event-error">${esc(uiText(event.error))}</p>` : ''}${event.input != null ? `<h4>Input</h4><pre>${esc(serialize(event.input))}</pre>` : ''}${event.output != null ? `<h4>Output</h4><pre>${esc(serialize(event.output))}</pre>` : ''}</div></details>`).join('')}</div>`;
}
