import { state, api, esc, toast, uiText } from './core.js';
import { icon } from './icons.js';
import { button } from './components.js';

const dialog = document.querySelector('#app-dialog');
const workspaceDialog = document.querySelector('#workspace-dialog');
let onSaved = () => {};
let pendingAgentSkillSection = '';
export function setDialogRefresh(callback) { onSaved = callback; }
export function closeDialog() { if (dialog.querySelector('[data-pending="true"]')) return; dialog.close(); }
dialog.addEventListener('click', event => { if (event.target.closest('[data-dialog-close]')) closeDialog(); });
dialog.addEventListener('cancel', event => { if (dialog.querySelector('[data-pending="true"]')) event.preventDefault(); });
function open(title, subtitle, content, submitLabel, handler, wide = false, danger = false) {
  if (pendingAgentSkillSection && (title === 'Configure agent' || title === 'Create a new agent')) {
    content += pendingAgentSkillSection;
    pendingAgentSkillSection = '';
  }
  dialog.className = wide ? 'wide-dialog' : '';
  dialog.innerHTML = `<form id="dialog-form"><header class="dialog-header"><div><span class="eyebrow">AGENT CONTROL CENTER</span><h2 id="dialog-title">${esc(title)}</h2><p>${esc(subtitle)}</p></div><button type="button" class="icon-button" data-dialog-close aria-label="Close">${icon('close')}</button></header><div class="dialog-body">${content}</div><div class="dialog-error" role="alert" hidden></div><footer class="dialog-footer"><button type="button" class="button secondary" data-dialog-close>Cancel</button><button type="submit" class="button ${danger ? 'danger' : 'primary'}" id="dialog-submit">${esc(submitLabel)}</button></footer></form>`;
  dialog.showModal();
  dialog.querySelector('form').addEventListener('submit', async event => {
    event.preventDefault(); const form = event.currentTarget, errorBox = dialog.querySelector('.dialog-error'), submit = dialog.querySelector('#dialog-submit');
    if (form.dataset.pending === 'true') return;
    const data = new FormData(form); errorBox.hidden = true; form.dataset.pending = 'true'; submit.disabled = true; submit.innerHTML = `<span class="spinner"></span> Saving…`;
    try { await handler(data, form); dialog.close(); await onSaved(); }
    catch (error) { errorBox.textContent = error.message; errorBox.hidden = false; }
    finally { form.dataset.pending = 'false'; submit.disabled = false; submit.textContent = submitLabel; }
  });
}
function field(label, name, value = '', options = {}) {
  const { type = 'text', min, max, step, required, hint, placeholder, span, rows = 3 } = options;
  return `<label class="form-field ${span ? 'full-width' : ''}"><span>${esc(label)}${required ? ' <b>*</b>' : ''}</span>${type === 'textarea' ? `<textarea name="${name}" rows="${rows}" ${required ? 'required' : ''} placeholder="${esc(placeholder || '')}">${esc(value)}</textarea>` : `<input type="${type}" name="${name}" value="${esc(value)}" ${required ? 'required' : ''} ${min == null ? '' : `min="${min}"`} ${max == null ? '' : `max="${max}"`} ${step == null ? '' : `step="${step}"`} placeholder="${esc(placeholder || '')}" ${name === 'model' ? 'list="model-options"' : ''}>`}${hint ? `<small>${esc(hint)}</small>` : ''}</label>`;
}
function workspaceField(value = '') {
  return `<label class="form-field full-width"><span>Agent workspace</span><div class="workspace-input-row"><input type="text" name="workspace_path" value="${esc(value)}" placeholder="Empty: a new workspace will be created for each task"><button type="button" class="button secondary" id="select-workspace">${icon('folder')} Choose folder</button></div><small>The folder must already exist. The agent will work directly in it, and changes will persist between tasks. Clear this field to use a fresh, isolated workspace.</small></label>`;
}
async function browseWorkspace(path = '') {
  const result = await api(`/workspaces/browse?${new URLSearchParams(path ? { path } : {})}`);
  workspaceDialog.dataset.path = result.path;
  workspaceDialog.querySelector('#workspace-browser-path').value = result.path;
  const list = workspaceDialog.querySelector('#workspace-browser-list');
  list.innerHTML = result.directories.length ? result.directories.map(item => `<button type="button" class="workspace-folder" data-browse-path="${esc(item.path)}">${icon('folder')}<span>${esc(item.name)}</span>${icon('chevron')}</button>`).join('') : '<div class="workspace-empty">No accessible subfolders.</div>';
  const up = workspaceDialog.querySelector('#workspace-up'); up.disabled = !result.parent; up.dataset.browsePath = result.parent || '';
  workspaceDialog.querySelector('#workspace-current').textContent = result.writable ? 'The current user can write to this folder.' : 'This folder may be read-only.';
  workspaceDialog.querySelector('#workspace-truncated').hidden = !result.truncated;
}
async function openWorkspacePicker(target = dialog.querySelector('[name="workspace_path"]')) {
  workspaceDialog.innerHTML = `<div class="workspace-browser"><header class="dialog-header"><div><span class="eyebrow">LOCAL WORKSPACE</span><h2 id="workspace-dialog-title">Choose folder</h2><p>Choose the root folder where the agent can read and modify files.</p></div><button type="button" class="icon-button" data-workspace-close aria-label="Close">${icon('close')}</button></header><div class="workspace-browser-toolbar"><button type="button" class="button secondary" id="workspace-up">${icon('back')} Up</button><input id="workspace-browser-path" type="text" aria-label="Absolute path"><button type="button" class="button secondary" id="workspace-go">Go</button></div><div class="dialog-error" id="workspace-error" role="alert" hidden></div><div id="workspace-browser-list" class="workspace-browser-list"><span class="spinner"></span></div><p id="workspace-truncated" class="small muted" hidden>Showing the first 500 folders.</p><footer class="dialog-footer workspace-browser-footer"><span><strong id="workspace-current"></strong></span><button type="button" class="button secondary" data-workspace-close>Cancel</button><button type="button" class="button primary" id="workspace-select-current">Use this folder</button></footer></div>`;
  workspaceDialog.showModal();
  const showError = error => { const box = workspaceDialog.querySelector('#workspace-error'); box.textContent = error.message; box.hidden = false; };
  const navigate = async path => { workspaceDialog.querySelector('#workspace-error').hidden = true; try { await browseWorkspace(path); } catch (error) { showError(error); } };
  workspaceDialog.onclick = event => {
    if (event.target.closest('[data-workspace-close]')) return workspaceDialog.close();
    const folder = event.target.closest('[data-browse-path]'); if (folder) return navigate(folder.dataset.browsePath);
    if (event.target.closest('#workspace-go')) return navigate(workspaceDialog.querySelector('#workspace-browser-path').value.trim());
    if (event.target.closest('#workspace-select-current')) { target.value = workspaceDialog.dataset.path; workspaceDialog.close(); }
  };
  workspaceDialog.querySelector('#workspace-browser-path').addEventListener('keydown', event => { if (event.key === 'Enter') { event.preventDefault(); navigate(event.currentTarget.value.trim()); } });
  await navigate(target.value.trim());
}
export async function chooseWorkspace(target) { await openWorkspacePicker(target); if (target?.id === 'freya-workspace') { state.freyaDraft.workspace_path = target.value; target.dispatchEvent(new Event('input', { bubbles: true })); } }
function capabilityRule(policy, id) {
  const [category, action] = id.split('.');
  return policy?.capabilities?.[category]?.[action] || { mode: 'deny' };
}
function legacyCapabilityPolicy(c, tools) {
  const mode = c.permissions === 'execute' ? 'allow' : c.permissions === 'workspace' ? 'allow' : 'deny';
  const selected = new Set(tools), result = { capabilities: {} };
  (state.config?.capability_catalog || []).forEach(cap => {
    const enabled = selected.has(cap.tool);
    let allowed = enabled && ['filesystem.list', 'filesystem.read', 'filesystem.search', 'git.diff'].includes(cap.id);
    if (enabled && mode === 'allow' && cap.id.startsWith('filesystem.') && !['filesystem.list', 'filesystem.read', 'filesystem.search'].includes(cap.id)) allowed = true;
    if (enabled && c.permissions === 'execute' && cap.id.startsWith('execution.')) allowed = true;
    if (enabled && c.permissions === 'execute' && cap.id === 'git.status') allowed = true;
    const [category, action] = cap.id.split('.'); (result.capabilities[category] ||= {})[action] = { mode: allowed ? 'allow' : 'deny' };
  });
  return result;
}
function capabilityEditor(policy) {
  const groups = [['filesystem', 'Filesystem', ['list', 'read', 'search', 'create', 'modify', 'overwrite']], ['execution', 'Execution', ['python_script', 'pytest', 'unittest', 'py_compile', 'ruff']], ['git', 'Git', ['status', 'diff']]];
  return groups.map(([category, label, actions]) => `<section class="capability-group"><h4>${label}</h4><div class="capability-grid">${actions.map(action => { const id = `${category}.${action}`, rule = capabilityRule(policy, id); return `<label class="capability-row"><span>${action.replaceAll('_', ' ')}</span><select name="cap_mode_${id}"><option value="deny" ${rule.mode === 'deny' ? 'selected' : ''}>Deny</option><option value="ask" ${rule.mode === 'ask' ? 'selected' : ''}>Ask</option><option value="allow" ${rule.mode === 'allow' ? 'selected' : ''}>Allow</option></select>${category === 'filesystem' && ['create', 'modify', 'overwrite'].includes(action) ? `<input name="cap_paths_${id}" value="${esc((rule.paths || []).join(', '))}" placeholder="Allowed paths (optional)"><input name="cap_extensions_${id}" value="${esc((rule.extensions || []).join(', '))}" placeholder="Extensions (optional)"><input type="number" name="cap_max_${id}" value="${rule.max_bytes ?? ''}" min="0" placeholder="Max bytes (optional)">` : ''}</label>`; }).join('')}</div></section>`).join('');
}
function skillContextPreview(skill) {
  if (!skill) return 'Save the skill to preview its normalized context.';
  const lines = [`## ${skill.name}`, `Version: ${skill.version}`, `Category: ${skill.category || 'General'}`, '', skill.description || ''];
  if (skill.instructions?.length) lines.push('', 'Instructions:', ...skill.instructions.map(item => `- ${item}`));
  if (skill.procedures?.length) { lines.push('', 'Relevant procedures:'); skill.procedures.forEach(procedure => { lines.push(`### ${procedure.name}`); (procedure.steps || []).forEach((step, index) => lines.push(`${index + 1}. ${step}`)); }); }
  if (skill.required_capabilities?.length) lines.push('', 'Required capabilities: ' + skill.required_capabilities.join(', '));
  if (skill.recommended_capabilities?.length) lines.push('Recommended capabilities: ' + skill.recommended_capabilities.join(', '));
  return lines.join('\n');
}
export async function agentDialog(id) {
  const agent = id ? await api(`/agents/${encodeURIComponent(id)}`) : null;
  const c = { ...(state.config?.defaults || {}), ...(agent?.config || {}) }, selectedTools = agent?.tools || state.config?.default_tools || [], policy = agent?.capability_policy || c.capability_policy || legacyCapabilityPolicy(c, selectedTools);
  const identity = c.identity || {}, behavior = c.behavior || {}, autonomy = c.autonomy || {}, verification = c.verification || {}, output = c.output || {};
  const lines = value => (value || []).join('\n');
  const assigned = new Map((agent?.skills || []).map(skill => [skill.id, skill]));
  const skillRows = (state.skills || []).map(skill => {
    const current = assigned.get(skill.id), missing = current?.missing_required_capabilities || [], recommended = current?.missing_recommended_capabilities || [];
    return `<label class="skill-assignment-row"><input type="checkbox" name="assigned_skill" value="${esc(skill.id)}" ${current ? 'checked' : ''}><span><strong>${esc(skill.name)}</strong><small>${esc(skill.category || 'General')} · v${skill.version}${current?.operational ? ' · Operational' : current ? ' · Missing required capability' : ''}</small>${missing.length ? `<em>Missing required: ${esc(missing.join(', '))}</em>` : ''}${recommended.length ? `<em>Recommended missing: ${esc(recommended.join(', '))}</em>` : ''}</span><input class="skill-priority" type="number" name="skill_priority_${esc(skill.id)}" value="${current?.priority ?? 0}" min="-1000000" max="1000000" aria-label="Priority for ${esc(skill.name)}"><a href="#/skills/${esc(skill.id)}">Open</a></label>`;
  }).join('');
  const skillSection = `<details class="form-section"><summary class="form-section-title">${icon('spark')}<div><h3>Skills</h3><p>Reusable knowledge and procedures; capabilities remain controlled by Policy.</p></div></summary><div class="skill-assignment-list">${skillRows || '<p class="muted">No skills configured. Create one from the Skills page.</p>'}</div></details>`;
  pendingAgentSkillSection = skillSection;
  const content = `<section class="form-section"><div class="form-section-title">${icon('agents')}<div><h3>General</h3><p>Define who this agent is and what it is for.</p></div></div><div class="form-grid">${field('Name', 'name', agent?.name, { required: true, placeholder: 'e.g. Atlas' })}${field('Role', 'role', agent?.role, { required: true, placeholder: 'e.g. Senior Software Engineer' })}${field('Purpose', 'purpose', identity.purpose, { span: true, placeholder: 'What outcome is this agent responsible for?' })}${field('Description', 'description', agent?.description || identity.description, { span: true, placeholder: 'Short description' })}<label class="checkbox-label full-width"><input type="checkbox" name="enabled" ${agent?.enabled !== false ? 'checked' : ''}>Agent enabled · can receive new tasks</label></div></section>
    <details class="form-section" open><summary class="form-section-title">${icon('agents')}<div><h3>Identity details</h3><p>Responsibilities and constraints become part of the model context.</p></div></summary><div class="form-grid">${field('Responsibilities', 'responsibilities', lines(identity.responsibilities), { type: 'textarea', span: true, hint: 'One responsibility per line.' })}${field('Constraints', 'constraints', lines(identity.constraints), { type: 'textarea', span: true, hint: 'One constraint per line.' })}${field('Additional instructions', 'instructions', agent?.instructions, { type: 'textarea', rows: 4, span: true, hint: 'Specific guidance only; system policy and capability policy always win.' })}${field('Legacy system guidance', 'system_prompt', uiText(c.system_prompt), { type: 'textarea', rows: 3, span: true, hint: 'Kept for compatibility; never overrides system or capability policy.' })}</div></details>
    <details class="form-section"><summary class="form-section-title">${icon('activity')}<div><h3>Behavior</h3><p>How the agent plans, handles ambiguity, and recovers from errors.</p></div></summary><div class="form-grid three"><label class="form-field"><span>Planning</span><select name="planning_mode">${[['direct','Direct'],['adaptive','Adaptive'],['explicit','Explicit']].map(([v,l]) => `<option value="${v}" ${(behavior.planning?.mode || 'adaptive') === v ? 'selected' : ''}>${l}</option>`).join('')}</select></label><label class="form-field"><span>Ambiguity</span><select name="ambiguity_mode">${[['ask','Ask'],['infer_when_safe','Infer when safe'],['best_effort','Best effort']].map(([v,l]) => `<option value="${v}" ${(behavior.ambiguity?.mode || 'infer_when_safe') === v ? 'selected' : ''}>${l}</option>`).join('')}</select></label>${field('Repeated failure limit', 'repeated_failure_limit', behavior.persistence?.repeated_failure_limit ?? 2, { type: 'number', min: 1, max: 10 })}</div><div class="form-grid"><label class="checkbox-label"><input type="checkbox" name="prefer_minimal_changes" ${behavior.change_strategy?.prefer_minimal_changes !== false ? 'checked' : ''}>Prefer minimal changes</label><label class="checkbox-label"><input type="checkbox" name="inspect_before_modify_existing" ${behavior.change_strategy?.inspect_before_modify_existing !== false ? 'checked' : ''}>Inspect existing resources before modifying</label><label class="checkbox-label"><input type="checkbox" name="retry_recoverable_errors" ${behavior.persistence?.retry_recoverable_errors !== false ? 'checked' : ''}>Retry recoverable errors</label></div></details>
    <details class="form-section"><summary class="form-section-title">${icon('play')}<div><h3>Autonomy</h3><p>Decision preferences; these never grant capabilities.</p></div></summary><div class="form-grid three">${[['task_decomposition','Task decomposition'],['implementation_choices','Implementation decisions'],['run_verification','Run verification'],['destructive_actions','Destructive decisions'],['request_missing_capabilities','Request missing capabilities']].map(([key,label]) => `<label class="form-field"><span>${label}</span><select name="autonomy_${key}">${['automatic','ask','deny'].map(v => `<option value="${v}" ${(autonomy[key] || (key === 'destructive_actions' ? 'ask' : 'automatic')) === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label>`).join('')}<label class="checkbox-label"><input type="checkbox" name="stop_when_blocked" ${autonomy.stop_when_blocked !== false ? 'checked' : ''}>Stop when blocked</label></div></details>
    <details class="form-section"><summary class="form-section-title">${icon('check')}<div><h3>Verification</h3><p>Evidence and completion criteria sent to the worker.</p></div></summary><div class="form-grid"><label class="checkbox-label"><input type="checkbox" name="verification_enabled" ${verification.enabled !== false ? 'checked' : ''}>Verification enabled</label><label class="checkbox-label"><input type="checkbox" name="require_tool_evidence" ${verification.require_tool_evidence !== false ? 'checked' : ''}>Require tool evidence</label><label class="checkbox-label"><input type="checkbox" name="run_available_tests" ${verification.run_available_tests !== false ? 'checked' : ''}>Run available tests</label><label class="checkbox-label"><input type="checkbox" name="inspect_changes" ${verification.inspect_changes !== false ? 'checked' : ''}>Inspect changes</label>${field('Completion criteria', 'completion_criteria', lines(verification.completion_criteria), { type: 'textarea', span: true, hint: 'One criterion per line.' })}</div></details>
    <details class="form-section"><summary class="form-section-title">${icon('file')}<div><h3>Output contract</h3><p>Choose text or a normalized structured result.</p></div></summary><div class="form-grid"><label class="form-field"><span>Format</span><select name="output_format"><option value="text" ${(output.format || 'text') === 'text' ? 'selected' : ''}>Text</option><option value="structured" ${output.format === 'structured' ? 'selected' : ''}>Structured</option></select></label><label class="form-field full-width"><span>Included fields</span><input name="output_include" value="${esc((output.include || ['summary','actions','artifacts','verification','limitations']).join(', '))}" placeholder="summary, actions, artifacts, verification, limitations"></label></div></details>
    <section class="form-section"><div class="form-section-title">${icon('cpu')}<div><h3>Model</h3><p>Connect a model available on your Ollama server.</p></div></div><div class="form-grid">${field('Ollama endpoint', 'endpoint', c.endpoint || 'http://127.0.0.1:11434', { required: true, type: 'url' })}${field('Model', 'model', c.model, { required: true, placeholder: 'qwen2.5-coder:3b' })}<datalist id="model-options"></datalist><div class="model-check full-width"><span id="model-status" class="muted small">Check installed models or enter a model name.</span><button type="button" class="button small-button" id="load-models">${icon('refresh')} Detect models</button></div>${field('Temperature', 'temperature', c.temperature ?? .2, { type: 'number', min: 0, max: 2, step: .05 })}${field('Context window', 'context_window', c.context_window ?? 8192, { type: 'number', min: 512, max: 131072, step: 1 })}${field('Token environment variable (optional)', 'secret_env', c.secret_env, { span: true, placeholder: 'ACC_SECRET_OLLAMA', hint: 'Enter only an ACC_SECRET_... variable name from the server environment, never the secret value.' })}</div></section>
    <section class="form-section"><div class="form-section-title">${icon('folder')}<div><h3>Workspace</h3><p>Choose the folder where this agent will work.</p></div></div><div class="form-grid">${workspaceField(c.workspace_path)}</div><div class="notice workspace-warning">${icon('shield')} Tools remain limited to this folder and its allowed relative directories. The Execute permission can start local code with your user permissions.</div></section>
    <section class="form-section"><div class="form-section-title">${icon('shield')}<div><h3>Capabilities</h3><p>Choose the action, scope, and decision required for each operation.</p></div></div>${capabilityEditor(policy)}<p class="small muted">Ask records approval_required and safely skips the tool. Paths are workspace-relative; empty lists mean no path or extension restriction.</p></section>
    <details class="advanced-tools"><summary>Advanced tool mapping</summary><div class="tool-options">${state.tools.map(tool => `<label class="tool-option ${tool.available ? '' : 'unavailable'}"><input type="checkbox" name="tools" value="${esc(tool.name)}" ${selectedTools.includes(tool.name) && tool.available ? 'checked' : ''} ${tool.available ? '' : 'disabled'}><span><strong>${esc(tool.name)}</strong><small>${esc(tool.available ? tool.description : 'Unavailable in this version')}</small></span></label>`).join('')}</div></details>
    <section class="form-section"><div class="form-section-title">${icon('shield')}<div><h3>Limits and permissions</h3><p>Set explicit limits for every task.</p></div></div><div class="form-grid three">${field('Maximum steps', 'max_steps', c.max_steps ?? 20, { type: 'number', min: 1, max: 100 })}${field('Maximum time (s)', 'max_seconds', c.max_seconds ?? 300, { type: 'number', min: 1, max: 86400 })}${field('Token budget', 'max_tokens', c.max_tokens ?? 16384, { type: 'number', min: 128, max: 1000000 })}${field('Model calls', 'max_model_calls', c.max_model_calls ?? 20, { type: 'number', min: 1, max: 100 })}${field('Tool calls', 'max_tool_calls', c.max_tool_calls ?? 40, { type: 'number', min: 0, max: 1000 })}${field('Retries per action', 'retries', c.retries ?? 1, { type: 'number', min: 0, max: 3 })}</div><div class="form-grid permission-grid"><label class="form-field full-width"><span>Agent permissions</span><select name="permissions">${[['read_only', 'Read only'], ['workspace', 'Read and write in the workspace'], ['execute', 'Read, write, and run allowed commands']].map(([value, label]) => `<option value="${value}" ${c.permissions === value ? 'selected' : ''}>${label}</option>`).join('')}</select><small>Running commands can start local processes and tests inside the workspace. Enable this only if you trust the model and task files.</small></label>${field('Allowed directories', 'allowed_directories', (c.allowed_directories || ['.']).join('\n'), { type: 'textarea', hint: 'One relative path per line. “.” includes the entire workspace; paths cannot escape it.' })}${field('Blocked commands', 'forbidden_commands', (c.forbidden_commands || []).join('\n'), { type: 'textarea', hint: 'One command name per line. This is applied in addition to the allowlist.' })}</div></section>`;
  open(id ? 'Configure agent' : 'Create a new agent', id ? 'Update the model, tools, and limits.' : 'A real agent with a defined model and scope.', content, id ? 'Save changes' : 'Create agent', async data => {
    const config = {};
    for (const key of ['model', 'endpoint', 'system_prompt', 'permissions', 'secret_env', 'workspace_path']) config[key] = String(data.get(key) || '').trim();
    for (const key of ['temperature', 'context_window', 'max_tokens', 'max_steps', 'max_seconds', 'max_model_calls', 'max_tool_calls', 'retries']) config[key] = Number(data.get(key));
    for (const key of ['allowed_directories', 'forbidden_commands']) config[key] = String(data.get(key) || '').split(/\r?\n/).map(value => value.trim()).filter(Boolean);
    const list = key => String(data.get(key) || '').split(/\r?\n/).map(value => value.trim()).filter(Boolean);
    config.identity = { purpose: String(data.get('purpose') || '').trim(), responsibilities: list('responsibilities'), constraints: list('constraints') };
    config.behavior = { planning: { mode: String(data.get('planning_mode') || 'adaptive') }, ambiguity: { mode: String(data.get('ambiguity_mode') || 'infer_when_safe') }, persistence: { retry_recoverable_errors: data.has('retry_recoverable_errors'), repeated_failure_limit: Number(data.get('repeated_failure_limit') || 2), change_strategy_after_failure: true }, change_strategy: { prefer_minimal_changes: data.has('prefer_minimal_changes'), inspect_before_modify_existing: data.has('inspect_before_modify_existing') } };
    config.autonomy = { task_decomposition: String(data.get('autonomy_task_decomposition') || 'automatic'), implementation_choices: String(data.get('autonomy_implementation_choices') || 'automatic'), create_files: 'automatic', modify_files: 'automatic', run_verification: String(data.get('autonomy_run_verification') || 'automatic'), destructive_actions: String(data.get('autonomy_destructive_actions') || 'ask'), request_missing_capabilities: String(data.get('autonomy_request_missing_capabilities') || 'automatic'), request_new_capabilities: String(data.get('autonomy_request_missing_capabilities') || 'automatic'), stop_when_blocked: data.has('stop_when_blocked') };
    config.verification = { enabled: data.has('verification_enabled'), inspect_changes: data.has('inspect_changes'), run_available_tests: data.has('run_available_tests'), require_tool_evidence: data.has('require_tool_evidence'), completion_criteria: list('completion_criteria') };
     config.output = { format: String(data.get('output_format') || 'text'), include: String(data.get('output_include') || '').split(',').map(value => value.trim()).filter(Boolean) };
     const skills = data.getAll('assigned_skill').map(skillId => ({ id: String(skillId), priority: Number(data.get(`skill_priority_${skillId}`) || 0) }));
    const capabilities = { capabilities: {} };
    for (const category of ['filesystem', 'execution', 'git']) { capabilities.capabilities[category] = {}; const actions = category === 'filesystem' ? ['list', 'read', 'search', 'create', 'modify', 'overwrite'] : category === 'execution' ? ['python_script', 'pytest', 'unittest', 'py_compile', 'ruff'] : ['status', 'diff']; for (const action of actions) { const id = `${category}.${action}`, rule = { mode: data.get(`cap_mode_${id}`) || 'deny' }; const paths = String(data.get(`cap_paths_${id}`) || '').split(',').map(v => v.trim()).filter(Boolean); const extensions = String(data.get(`cap_extensions_${id}`) || '').split(',').map(v => v.trim()).filter(Boolean); const max = String(data.get(`cap_max_${id}`) || '').trim(); if (paths.length) rule.paths = paths; if (extensions.length) rule.extensions = extensions; if (max) rule.max_bytes = Number(max); capabilities.capabilities[category][action] = rule; } }
     const saved = await api(id ? `/agents/${id}` : '/agents', id ? 'PATCH' : 'POST', { name: data.get('name'), description: data.get('description'), role: data.get('role'), instructions: data.get('instructions'), enabled: data.has('enabled'), skills, config, capability_policy: capabilities, tools: data.getAll('tools') });
    toast(id ? 'Settings saved.' : 'Agent created.'); if (!id) location.hash = `#/agents/${saved.id}`;
  }, true);
  dialog.querySelector('#select-workspace').addEventListener('click', () => openWorkspacePicker());
  dialog.querySelector('#load-models').addEventListener('click', async event => {
    const button = event.currentTarget, status = dialog.querySelector('#model-status'); button.disabled = true; status.textContent = 'Checking Ollama…';
    try { const result = await api(`/models?${new URLSearchParams({ endpoint: dialog.querySelector('[name="endpoint"]').value })}`); dialog.querySelector('#model-options').innerHTML = (result.models || []).map(model => `<option value="${esc(model.name)}">`).join(''); status.textContent = result.error || `${result.models.length} models available. Choose one in the Model field.`; status.className = `small ${result.error ? 'text-red' : 'text-green'}`; }
    catch (error) { status.textContent = error.message; status.className = 'small text-red'; } finally { button.disabled = false; }
  });
}

export async function skillDialog(id) {
  const skill = id ? await api(`/skills/${encodeURIComponent(id)}`) : null;
  const procedureText = JSON.stringify(skill?.procedures || [{ name: 'Procedure', description: '', steps: [''] }], null, 2);
  const content = `<section class="form-section"><div class="form-section-title">${icon('spark')}<div><h3>General</h3><p>Stable IDs identify reusable knowledge independently from its display name.</p></div></div><div class="form-grid">${field('Skill ID', 'id', skill?.id, { required: true, placeholder: 'python-development', hint: id ? 'The ID is stable and cannot be changed.' : 'Lowercase letters, numbers, - or _.' })}${field('Name', 'name', skill?.name, { required: true })}${field('Category', 'category', skill?.category || 'General', { required: true })}${field('Version', 'version', skill?.version || 1, { type: 'number', min: 1, max: 1000000, required: true })}${field('Description', 'description', skill?.description, { type: 'textarea', span: true })}<label class="checkbox-label"><input type="checkbox" name="enabled" ${skill?.enabled !== false ? 'checked' : ''}>Enabled</label><label class="form-field"><span>Tags</span><input name="tags" value="${esc((skill?.tags || []).join(', '))}" placeholder="python, backend, debugging"></label></div></section><details class="form-section" open><summary class="form-section-title">${icon('edit')}<div><h3>Instructions</h3><p>General guidance for the specialty, expressed as one item per line.</p></div></summary><div class="form-grid">${field('Instructions', 'instructions', (skill?.instructions || []).join('\n'), { type: 'textarea', rows: 6, span: true })}</div></details><details class="form-section"><summary class="form-section-title">${icon('activity')}<div><h3>Procedures</h3><p>Recommended operating procedures. The model adapts irrelevant or unavailable steps.</p></div></summary><div class="form-grid">${field('Procedures JSON', 'procedures', procedureText, { type: 'textarea', rows: 12, span: true, hint: '[{"name":"Implement change","steps":["Inspect relevant files","Validate"]}]' })}</div></details><details class="form-section"><summary class="form-section-title">${icon('shield')}<div><h3>Capabilities</h3><p>Requirements and recommendations are diagnostics only; they never grant access.</p></div></summary><div class="form-grid">${field('Required capabilities', 'required_capabilities', (skill?.required_capabilities || []).join(', '), { span: true, placeholder: 'filesystem.read' })}${field('Recommended capabilities', 'recommended_capabilities', (skill?.recommended_capabilities || []).join(', '), { span: true, placeholder: 'filesystem.search, git.diff' })}</div></details><details class="form-section"><summary class="form-section-title">${icon('search')}<div><h3>Effective context preview</h3><p>Compact representation sent to an assigned worker.</p></div></summary><pre class="skill-preview">${esc(skillContextPreview(skill))}</pre></details>`;
  open(id ? 'Edit skill' : 'Create a skill', 'Define reusable knowledge without adding permissions.', content, id ? 'Save changes' : 'Create skill', async data => {
    let procedures;
    try { procedures = JSON.parse(String(data.get('procedures') || '[]')); } catch { throw new Error('Procedures must be valid JSON.'); }
    const split = key => String(data.get(key) || '').split(',').map(value => value.trim()).filter(Boolean);
    const payload = { id: String(data.get('id') || '').trim(), name: data.get('name'), category: data.get('category'), version: Number(data.get('version') || 1), description: data.get('description'), instructions: String(data.get('instructions') || '').split(/\r?\n/).map(value => value.trim()).filter(Boolean), procedures, required_capabilities: split('required_capabilities'), recommended_capabilities: split('recommended_capabilities'), tags: split('tags'), enabled: data.has('enabled') };
    const saved = await api(id ? `/skills/${encodeURIComponent(id)}` : '/skills', id ? 'PATCH' : 'POST', payload);
    toast(id ? 'Skill saved.' : 'Skill created.'); if (!id) location.hash = `#/skills/${saved.id}`;
  }, true);
}

export function assignDialog(id) {
  if (!state.agents.length) { toast('Create an agent before assigning a task.'); return agentDialog(); }
  const initialAgent = state.agents.find(agent => agent.id === id && agent.enabled) || state.agents.find(agent => agent.enabled) || state.agents[0];
  const content = `<div class="form-grid"><label class="form-field full-width"><span>Agent</span><select name="agent_id" required>${state.agents.map(agent => `<option value="${esc(agent.id)}" ${agent.id === initialAgent.id ? 'selected' : ''} ${agent.enabled ? '' : 'disabled'}>${esc(agent.name)} · ${esc(agent.config.model)}${agent.enabled ? '' : ' (disabled)'}</option>`).join('')}</select></label>${field('Task', 'prompt', '', { type: 'textarea', rows: 7, span: true, required: true, placeholder: 'Describe the goal, expected result, and task constraints…' })}<label class="form-field full-width"><span>Workspace for this task</span><div class="workspace-input-row"><input type="text" name="workspace_path" value="" placeholder="New automatic workspace"><button type="button" class="button secondary" id="select-task-workspace">${icon('folder')} Choose folder</button></div><small id="assigned-workspace-help"></small></label><div class="notice full-width workspace-warning">${icon('shield')} The agent's tools can read and modify files in the selected folder, subject to its permissions and allowed directories.</div></div>`;
  open('Assign a task', 'Choose the agent and workspace for this run.', content, 'Start run', async data => { const task = await api(`/agents/${data.get('agent_id')}/tasks`, 'POST', { prompt: data.get('prompt'), workspace_path: String(data.get('workspace_path') || '').trim() }); toast('Task created and queued.'); location.hash = `#/tasks/${task.id}`; });
  const select = dialog.querySelector('[name="agent_id"]'), workspace = dialog.querySelector('[name="workspace_path"]'), help = dialog.querySelector('#assigned-workspace-help');
  const refreshWorkspace = resetPath => {
    const agent = state.agents.find(item => item.id === select.value), path = agent?.config?.workspace_path || '';
    if (resetPath) workspace.value = path;
    help.textContent = path ? 'The configured folder is selected by default. You can change it for this task, or clear it to create a fresh workspace.' : 'Choose a folder for this task, or leave the field empty to create a fresh workspace.';
  };
  select.addEventListener('change', () => refreshWorkspace(true)); refreshWorkspace(true);
  dialog.querySelector('#select-task-workspace').addEventListener('click', () => openWorkspacePicker(workspace));
}

export function confirmAction({ title, description, label, action, danger = false }) {
  open(title, '', `<p class="confirm-description">${esc(description)}</p>`, label, async () => { await action(); }, false, danger);
}
