import { state, api, esc, number, compact, duration, date, bytes, query, serialize, liveTask } from './core.js';
import { icon } from './icons.js';
import { badge, button, heading, panelHeading, empty, stat, progress, taskTable, agentCard, chart, barChart, timeline, logTable } from './components.js';

const agentOptions = selected => `<option value="">Todos los agentes</option>${state.agents.map(a => `<option value="${esc(a.id)}" ${selected === a.id ? 'selected' : ''}>${esc(a.name)}</option>`).join('')}`;
const tabs = (items, selected, action) => `<div class="tabs" role="tablist">${items.map(([value, label]) => `<button role="tab" aria-selected="${selected === value}" class="tab ${selected === value ? 'active' : ''}" data-action="${action}" data-value="${value}">${label}</button>`).join('')}</div>`;
const chartTabs = () => tabs([['tasks', 'Tareas'], ['tokens', 'Tokens'], ['errors', 'Errores'], ['duration_seconds', 'Duración']], state.chart, 'chart');

export function dashboard() {
  const m = state.metrics || {}, h = state.health || {}, system = h.system || {};
  return `${heading('Centro de operaciones', 'Una vista clara de tus agentes, ejecuciones y recursos.', button('Asignar tarea', 'assign', 'play', '', 'secondary') + button('Crear agente', 'create-agent', 'plus', '', 'primary'), 'OVERVIEW')}
    <div class="stats-grid">${stat('Agentes totales', number(m.total_agents), 'agents', `<span class="mini-dot"></span> ${number(m.active_agents)} activos · ${number(m.running_agents)} ejecutando`)}${stat('Tareas ejecutadas', number(m.total_tasks), 'tasks', `<span class="text-green">${number(m.successful_tasks)} exitosas</span><span class="note-separator">·</span>${number(m.failed_tasks)} fallidas`)}${stat('Tokens consumidos', compact(m.total_tokens), 'bolt', `${number(m.model_calls)} llamadas al modelo`)}${stat('Tiempo promedio', duration(m.avg_duration_seconds), 'clock', `Por tarea completada`)}</div>
    <div class="dashboard-grid"><section class="panel activity-panel">${panelHeading('Actividad de ejecución', 'Historial real de los últimos 7 días · UTC', '<span class="subtle-tag">Últimos 7 días</span>')}${chartTabs()}<div class="chart-body">${chart(m.history, state.chart)}</div></section>
      <section class="panel runtime-panel">${panelHeading('Estado del sistema', 'Infraestructura local', `<span class="online-dot"></span>`)}<div class="runtime-status">${icon('cpu')}<div><strong>Agent Runtime</strong><span>${h.status === 'ok' ? 'Operativo' : 'Conectando'}</span></div><span class="badge success">Local</span></div><div class="resource"><div><span>CPU</span><strong class="mono">${system.cpu_percent == null ? 'N/D' : `${number(system.cpu_percent)}%`}</strong></div><div class="resource-track"><span style="width:${Math.min(100, Math.max(0, system.cpu_percent || 0))}%"></span></div></div><div class="resource"><div><span>Memoria RAM</span><strong class="mono">${system.ram_percent == null ? 'N/D' : `${number(system.ram_percent)}%`}</strong></div><div class="resource-track"><span style="width:${Math.min(100, Math.max(0, system.ram_percent || 0))}%"></span></div><p>${system.ram_total_bytes ? `${bytes(system.ram_used_bytes)} de ${bytes(system.ram_total_bytes)}` : 'Telemetría no disponible en este sistema'}</p></div><div class="runtime-facts"><div><span>Workers simultáneos</span><strong>${number(h.runtime?.max_workers)}</strong></div><div><span>Base de datos</span><strong>${esc(h.database || '—')}</strong></div><div><span>Agentes con errores</span><strong class="${m.error_agents ? 'text-red' : ''}">${number(m.error_agents)}</strong></div></div></section></div>
    <section class="panel recent-tasks">${panelHeading('Ejecuciones recientes', 'Del primer paso al resultado final', '<a class="text-link" href="#/tasks">Ver todas las tareas ' + icon('arrow') + '</a>')}${taskTable(state.tasks.slice(0, 5), { small: true })}</section>
    <section class="agents-preview">${panelHeading('Tus agentes', `${number(m.total_agents)} agentes en este workspace`, '<a class="text-link" href="#/agents">Administrar agentes ' + icon('arrow') + '</a>')}${state.agents.length ? `<div class="agent-grid">${state.agents.slice(0, 3).map(agentCard).join('')}</div>` : `<div class="onboarding-strip"><div class="onboarding-icon">${icon('agents')}</div><div><h3>Tu equipo de agentes empieza aquí</h3><p>Conecta un modelo, elige sus herramientas y dale su primera tarea.</p></div>${button('Crear primer agente', 'create-agent', 'plus', '', 'secondary')}</div>`}</section>`;
}

export function agents() {
  return `${heading('Agents', 'Configura y coordina tu equipo de agentes de IA.', button('Crear agente', 'create-agent', 'plus', '', 'primary'), 'WORKSPACE / AGENTS')}<div class="section-toolbar"><div class="counter-label">Todos los agentes <span>${number(state.agents.length)}</span></div><span class="muted small">${number(state.agents.filter(a => a.enabled).length)} activos · ejecución local</span></div>${state.agents.length ? `<div class="agent-grid">${state.agents.map(agentCard).join('')}</div>` : `<section class="panel big-empty">${empty('agents', 'Crea tu primer agente', 'Dale un nombre, conecta tu modelo de Ollama y selecciona las herramientas que podrá utilizar.', button('Crear agente', 'create-agent', 'plus', '', 'primary'))}<div class="setup-steps"><span><b>01</b> Configura un modelo</span><span><b>02</b> Elige sus herramientas</span><span><b>03</b> Asigna una tarea</span></div></section>`}`;
}

export async function agentDetail(id) {
  const [agent, tasks, metrics] = await Promise.all([api(`/agents/${id}`), api(`/tasks?agent_id=${encodeURIComponent(id)}`), api(`/metrics?agent_id=${encodeURIComponent(id)}`)]);
  const current = agent.current_task ? await api(`/tasks/${agent.current_task.id}`) : null;
  const attrs = `data-id="${esc(id)}"`, allTabs = [['timeline', 'Execution Timeline'], ['metrics', 'Metrics'], ['logs', 'Logs'], ['tools', 'Tools'], ['configuration', 'Configuration'], ['history', 'Task History']];
  let content = '';
  if (state.tab === 'timeline') content = `<section class="panel">${panelHeading('Timeline de ejecución', 'Acciones y explicaciones operativas. El razonamiento privado del modelo no se muestra.')}${current ? timeline(current.events || current.timeline) : tasks.length ? `<div class="panel-note">El agente no tiene una tarea activa. <a href="#/tasks/${esc(tasks[0].id)}">Ver su última ejecución ${icon('arrow')}</a></div>${timeline((await api(`/tasks/${tasks[0].id}`)).events)}` : empty('activity', 'El agente está listo', 'Asigna una tarea para ver sus acciones en tiempo real.', button('Asignar tarea', 'assign', 'play', attrs, 'primary'))}</section>`;
  else if (state.tab === 'metrics') content = metricsView(metrics, false);
  else if (state.tab === 'history') content = `<section class="panel">${panelHeading('Historial de tareas', 'Ejecuciones persistidas de este agente')}${taskTable(tasks)}</section>`;
  else if (state.tab === 'logs') content = `<section class="panel">${panelHeading('Logs del agente', 'Últimos 200 eventos', `<a class="text-link" href="#/logs?agent_id=${esc(id)}">Abrir filtros ${icon('arrow')}</a>`)}${logTable(await api(`/logs?agent_id=${encodeURIComponent(id)}&limit=200`))}</section>`;
  else if (state.tab === 'tools') content = `<section class="panel">${panelHeading('Herramientas habilitadas', 'El runtime aplica los permisos y límites del agente.', button('Configurar tools', 'edit-agent', 'settings', attrs, 'secondary'))}<div class="tool-grid">${state.tools.map(tool => `<div class="tool-card ${agent.tools.includes(tool.name) ? 'enabled' : ''}"><div>${icon(tool.dangerous ? 'terminal' : 'tool')}<strong class="mono">${esc(tool.name)}</strong>${agent.tools.includes(tool.name) ? '<span class="badge success">Habilitada</span>' : `<span class="subtle-tag">${tool.available ? 'Desactivada' : 'No disponible'}</span>`}</div><p>${esc(tool.description)}</p></div>`).join('')}</div></section>`;
  else content = `<section class="panel">${panelHeading('Configuración del agente', 'Los cambios se aplican a las próximas tareas.', button('Editar configuración', 'edit-agent', 'edit', attrs, 'secondary'))}<div class="config-view"><div class="key-values"><span>ID</span><code>${esc(agent.id)}</code><span>Rol</span><span>${esc(agent.role || '—')}</span><span>Creado</span><span>${date(agent.created_at, true)}</span>${Object.entries(agent.config).filter(([key]) => key !== 'system_prompt').map(([key, value]) => `<span>${esc(key)}</span><code>${esc(Array.isArray(value) ? value.join(', ') : value)}</code>`).join('')}</div><h3>System prompt</h3><pre>${esc(agent.config.system_prompt || 'Sin instrucciones adicionales')}</pre></div></section>`;
  return `<a class="back-link" href="#/agents">${icon('back')} Todos los agentes</a>${heading(agent.name, agent.description || agent.role || 'Agente local de propósito general', button('Configurar', 'edit-agent', 'settings', attrs, 'secondary') + button('Asignar tarea', 'assign', 'play', attrs, 'primary'), 'AGENT DETAIL')}<div class="agent-detail-summary"><div class="agent-detail-identity"><div class="avatar">${icon('agents')}</div><div>${badge(agent.status)}<span class="mono muted">${esc(agent.config.model)}</span></div></div><div class="agent-detail-controls">${button(agent.enabled ? 'Desactivar' : 'Activar', 'toggle-agent', '', `${attrs} data-enabled="${!agent.enabled}"`, 'small-button')}${button(agent.status === 'Paused' ? 'Reanudar' : 'Pausar', agent.status === 'Paused' ? 'resume-agent' : 'pause-agent', agent.status === 'Paused' ? 'play' : 'pause', attrs, 'small-button')}${button('Reiniciar', 'restart-agent', 'refresh', attrs, 'small-button')}${button('Duplicar', 'duplicate-agent', 'copy', attrs, 'small-button')}${button('Eliminar', 'delete-agent', 'trash', attrs, 'small-button danger-quiet')}</div></div><div class="current-task-card"><div><span class="eyebrow">TAREA ACTUAL</span><h3>${current ? `<a href="#/tasks/${esc(current.id)}">${esc(current.prompt)}</a>` : 'Sin tarea en ejecución'}</h3><p class="small muted">${current ? `${badge(current.status)} · ${duration(current.duration_seconds)} · ${number(current.tool_calls)} llamadas a herramientas` : 'Asigna una tarea cuando quieras iniciar una nueva ejecución.'}</p></div>${current ? `<div class="current-progress">${progress(current)}${button('Cancelar tarea', 'cancel-task', 'stop', `data-id="${esc(current.id)}"`, 'small-button danger-quiet')}</div>` : ''}</div>${agent.status === 'Paused' ? '<div class="notice">La pausa se aplica entre acciones. Una llamada al modelo o herramienta en curso puede terminar antes de detenerse.</div>' : ''}${tabs(allTabs, state.tab, 'agent-tab')}<div class="tab-content">${content}</div>`;
}

export async function tasks() {
  const filters = state.filters.tasks, items = await api(`/tasks?${query(filters)}`);
  return `${heading('Tasks', 'Cada ejecución, desde su inicio hasta el resultado.', button('Asignar tarea', 'assign', 'plus', '', 'primary'), 'WORKSPACE / TASKS')}<section class="panel"><div class="filter-bar"><div class="filter-label">${icon('filter')} Filtrar</div><select aria-label="Filtrar tareas por agente" data-filter="tasks" name="agent_id">${agentOptions(filters.agent_id)}</select><select aria-label="Filtrar tareas por estado" data-filter="tasks" name="status"><option value="">Todos los estados</option>${['Queued', 'Running', 'Paused', 'Success', 'Failed', 'Cancelled'].map(value => `<option ${filters.status === value ? 'selected' : ''}>${value}</option>`).join('')}</select><span class="filter-count">${number(items.length)} tareas</span></div>${taskTable(items)}</section>`;
}

export async function taskDetail(id) {
  const task = await api(`/tasks/${id}`), attrs = `data-id="${esc(id)}"`;
  const actions = liveTask(task) ? button(task.status === 'Paused' ? 'Reanudar agente' : 'Pausar agente', task.status === 'Paused' ? 'resume-agent' : 'pause-agent', task.status === 'Paused' ? 'play' : 'pause', `data-id="${esc(task.agent_id)}"`, 'secondary') + button('Cancelar', 'cancel-task', 'stop', attrs, 'danger') : button('Ejecutar otra vez', 'retry-task', 'refresh', attrs, 'primary');
  return `<a class="back-link" href="#/tasks">${icon('back')} Historial de tareas</a>${heading('Detalle de ejecución', task.id, actions, 'TASK EXECUTION')}<section class="panel task-overview"><div class="task-title-row"><h2>${esc(task.prompt)}</h2>${badge(task.status)}</div><div class="task-metadata"><span>${icon('agents')}<a href="#/agents/${esc(task.agent_id)}">${esc(task.agent_name)}</a></span><span>${icon('clock')}${date(task.started_at || task.created_at)}</span><span>${icon('cpu')}${esc(task.config.model)}</span></div>${progress(task)}<p class="small muted">El porcentaje indica el presupuesto de pasos utilizado; no estima cuánto falta para terminar.</p><div class="task-stats"><div><span>Duración</span><strong>${duration(task.duration_seconds)}</strong></div><div><span>Pasos</span><strong>${number(task.steps)}</strong></div><div><span>Tokens</span><strong>${compact(task.total_tokens)}</strong></div><div><span>Modelo / tools</span><strong>${number(task.model_calls)} / ${number(task.tool_calls)}</strong></div><div><span>Finalización</span><strong class="small">${date(task.finished_at)}</strong></div></div><details data-detail="workspace-${esc(id)}" class="workspace-detail"><summary>${icon('folder')} Workspace de ejecución</summary><code>${esc(task.workspace)}</code></details></section>${task.status === 'Paused' ? '<div class="notice">Pausa solicitada: el runtime espera entre acciones y conserva esta ejecución.</div>' : ''}${task.error ? `<div class="error-banner">${icon('alert')}<div><strong>Error de ejecución</strong><p>${esc(task.error)}</p></div></div>` : ''}${task.result ? `<section class="panel task-result">${panelHeading('Resultado', 'Respuesta final del agente')}<pre>${esc(serialize(task.result))}</pre></section>` : ''}<section class="panel">${panelHeading('Execution Timeline', 'Acciones, herramientas y resultados persistidos', `<span class="subtle-tag">${number((task.events || task.timeline || []).length)} eventos</span>`)}${timeline(task.events || task.timeline || [])}</section>`;
}

export async function logs() {
  const f = state.filters.logs, events = await api(`/logs?${query({ ...f, limit: 200 })}`);
  return `${heading('Logs', 'Explora el registro persistente de cada acción del sistema.', button('Actualizar', 'refresh', 'refresh', '', 'secondary'), 'OBSERVABILITY / LOGS')}<section class="panel"><form class="log-filters" id="log-filters"><label>Agente<select name="agent_id" data-filter="logs">${agentOptions(f.agent_id)}</select></label><label>Task ID<input name="task_id" value="${esc(f.task_id || '')}" placeholder="ID de la tarea" data-filter="logs"></label><label>Nivel<select name="level" data-filter="logs"><option value="">Todos los niveles</option>${['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'].map(v => `<option ${f.level === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label><label>Herramienta<select name="tool" data-filter="logs"><option value="">Todas las tools</option>${state.tools.map(t => `<option ${f.tool === t.name ? 'selected' : ''}>${esc(t.name)}</option>`).join('')}</select></label><label>Desde<input type="datetime-local" name="date_from" value="${esc(f.date_from || '')}" data-filter="logs"></label><label>Hasta<input type="datetime-local" name="date_to" value="${esc(f.date_to || '')}" data-filter="logs"></label><label class="checkbox-label"><input type="checkbox" name="error_only" data-filter="logs" ${f.error_only ? 'checked' : ''}>Solo errores</label>${button('Limpiar filtros', 'clear-logs', '', '', 'small-button')}</form><div class="log-table-header"><span>${number(events.length)} eventos · máximo 200</span><span>${icon('shield')} Contenido sensible sanitizado por el servidor</span></div>${logTable(events)}</section>`;
}

export function metricsView(m = {}, withHeading = true) {
  return `${withHeading ? heading('Metrics', 'Consumo, rendimiento y resultados de tus agentes.', '<span class="subtle-tag">Datos reales · últimos 7 días</span>', 'OBSERVABILITY / METRICS') : ''}<div class="stats-grid">${stat('Tareas exitosas', number(m.successful_tasks), 'check', `${number(m.total_tasks)} ejecuciones totales`)}${stat('Tareas fallidas', number(m.failed_tasks), 'alert', `${number(m.cancelled_tasks)} canceladas`)}${stat('Tokens consumidos', compact(m.total_tokens), 'bolt', `${number(m.model_calls)} llamadas al modelo`)}${stat('Tiempo promedio', duration(m.avg_duration_seconds), 'clock', `${number(m.avg_steps)} pasos por tarea`)}</div><div class="stats-grid secondary-stats">${stat('Llamadas a herramientas', number(m.tool_calls), 'tool', 'Total acumulado')}${stat('Llamadas al modelo', number(m.model_calls), 'cpu', 'Total acumulado')}${stat('Respuesta del modelo', duration(m.avg_model_seconds), 'activity', 'Duración promedio')}${stat('Tareas en ejecución', number(m.running_tasks), 'play', `${number(m.running_agents)} agentes trabajando`)}</div><section class="panel metrics-history">${panelHeading('Historial de actividad', 'Valores diarios registrados por el runtime · UTC')}${chartTabs()}<div class="chart-body">${chart(m.history, state.chart, true)}</div></section><div class="two-column"><section class="panel">${panelHeading('Herramientas más utilizadas', 'Llamadas acumuladas por herramienta')}${barChart(m.tools)}</section><section class="panel">${panelHeading('Errores por agente', 'Eventos de error registrados')}${barChart(m.errors_by_agent, 'errors')}</section></div>`;
}

export function settings() {
  const config = state.config || {}, h = state.health || {};
  return `${heading('Settings', 'Configuración de infraestructura y capacidades del workspace.', '', 'WORKSPACE / SETTINGS')}<div class="settings-grid"><section class="panel">${panelHeading('Workspace local', 'Configuración del servidor en ejecución')}<div class="settings-rows"><div><span>${icon('database')} Persistencia</span><strong>SQLite</strong></div><div><span>${icon('activity')} Actualizaciones en vivo</span><strong>Server-Sent Events</strong></div><div><span>${icon('cpu')} Workers simultáneos</span><strong>${number(h.runtime?.max_workers)}</strong></div><div><span>${icon('globe')} Proveedor del modelo</span><strong>Ollama</strong></div><div><span>${icon('folder')} Datos persistentes</span><code>${esc(config.data_dir || '—')}</code></div><div><span>${icon('folder')} Workspaces de tareas</span><code>${esc(config.workspaces_dir || '—')}</code></div></div><div class="panel-note">El modelo y sus límites se configuran por agente. Los parámetros de infraestructura se definen al iniciar el servidor.</div></section><section class="panel">${panelHeading('Seguridad por agente', 'Permisos explícitos y alcance limitado')}<div class="security-items"><article>${icon('shield')}<div><h3>Workspace aislado por ejecución</h3><p>Las lecturas y escrituras se limitan a los directorios autorizados de la tarea.</p></div></article><article>${icon('terminal')}<div><h3>Herramientas permitidas</h3><p>Solo se ejecutan tools habilitadas. Los comandos se validan contra una lista permitida.</p></div></article><article>${icon('logs')}<div><h3>Secrets fuera de la configuración</h3><p>Configura el nombre de una variable de entorno en el agente. No ingreses claves en prompts ni formularios.</p></div></article></div></section></div><section class="panel future-panel">${panelHeading('Capacidades de la plataforma', 'Esta versión prioriza la ejecución y observación local real.')}<div class="capabilities"><div><span>Agentes locales · Ollama</span><span class="badge success">Disponible</span></div><div><span>Cola local y ejecución concurrente</span><span class="badge success">Disponible</span></div><div><span>Logs persistentes y métricas</span><span class="badge success">Disponible</span></div>${['Workers remotos y contenedores', 'Planificación automática', 'Memoria persistente y RAG', 'Equipos y jerarquías de agentes', 'Web search, browser y conectores externos', 'Autenticación multiusuario'].map(label => `<div><span>${label}</span><span class="subtle-tag">No disponible</span></div>`).join('')}</div></section>`;
}
