import { state, api, esc, number, compact, duration, date, bytes, query, serialize, liveTask, uiText } from './core.js';
import { icon } from './icons.js';
import { badge, button, heading, panelHeading, empty, stat, progress, taskTable, agentCard, chart, barChart, timeline, logTable } from './components.js';

const agentOptions = selected => `<option value="">All agents</option>${state.agents.map(a => `<option value="${esc(a.id)}" ${selected === a.id ? 'selected' : ''}>${esc(a.name)}</option>`).join('')}`;
const tabs = (items, selected, action) => `<div class="tabs" role="tablist">${items.map(([value, label]) => `<button role="tab" aria-selected="${selected === value}" class="tab ${selected === value ? 'active' : ''}" data-action="${action}" data-value="${value}">${label}</button>`).join('')}</div>`;
const chartTabs = () => tabs([['tasks', 'Tasks'], ['tokens', 'Tokens'], ['errors', 'Errors'], ['duration_seconds', 'Duration']], state.chart, 'chart');

export function dashboard() {
  const m = state.metrics || {}, h = state.health || {}, system = h.system || {};
  return `${heading('Operations dashboard', 'A clear view of your agents, runs, and resources.', button('Assign task', 'assign', 'play', '', 'secondary') + button('Create agent', 'create-agent', 'plus', '', 'primary'), 'OVERVIEW')}
    <div class="stats-grid">${stat('Total agents', number(m.total_agents), 'agents', `<span class="mini-dot"></span> ${number(m.active_agents)} active · ${number(m.running_agents)} running`)}${stat('Runs completed', number(m.total_tasks), 'tasks', `<span class="text-green">${number(m.successful_tasks)} succeeded</span><span class="note-separator">·</span>${number(m.failed_tasks)} failed`)}${stat('Tokens used', compact(m.total_tokens), 'bolt', `${number(m.model_calls)} model calls`)}${stat('Average time', duration(m.avg_duration_seconds), 'clock', `Per completed task`)}</div>
    <div class="dashboard-grid"><section class="panel activity-panel">${panelHeading('Execution activity', 'Actual history for the last 7 days · UTC', '<span class="subtle-tag">Last 7 days</span>')}${chartTabs()}<div class="chart-body">${chart(m.history, state.chart)}</div></section>
    <section class="panel runtime-panel">${panelHeading('System status', 'Local infrastructure', `<span class="online-dot"></span>`)}<div class="runtime-status">${icon('cpu')}<div><strong>Agent Runtime</strong><span>${h.status === 'ok' ? 'Online' : 'Connecting'}</span></div><span class="badge success">Local</span></div><div class="resource"><div><span>CPU</span><strong class="mono">${system.cpu_percent == null ? 'N/A' : `${number(system.cpu_percent)}%`}</strong></div><div class="resource-track"><span style="width:${Math.min(100, Math.max(0, system.cpu_percent || 0))}%"></span></div></div><div class="resource"><div><span>Memory</span><strong class="mono">${system.ram_percent == null ? 'N/A' : `${number(system.ram_percent)}%`}</strong></div><div class="resource-track"><span style="width:${Math.min(100, Math.max(0, system.ram_percent || 0))}%"></span></div><p>${system.ram_total_bytes ? `${bytes(system.ram_used_bytes)} of ${bytes(system.ram_total_bytes)}` : 'Telemetry is unavailable on this system'}</p></div><div class="runtime-facts"><div><span>Concurrent workers</span><strong>${number(h.runtime?.max_workers)}</strong></div><div><span>Database</span><strong>${esc(h.database || '—')}</strong></div><div><span>Agents with errors</span><strong class="${m.error_agents ? 'text-red' : ''}">${number(m.error_agents)}</strong></div></div></section></div>
    <section class="panel recent-tasks">${panelHeading('Recent runs', 'From the first step to the final result', '<a class="text-link" href="#/tasks">View all tasks ' + icon('arrow') + '</a>')}${taskTable(state.tasks.slice(0, 5), { small: true })}</section>
    <section class="agents-preview">${panelHeading('Your agents', `${number(m.total_agents)} agents in this workspace`, '<a class="text-link" href="#/agents">Manage agents ' + icon('arrow') + '</a>')}${state.agents.length ? `<div class="agent-grid">${state.agents.slice(0, 3).map(agentCard).join('')}</div>` : `<div class="onboarding-strip"><div class="onboarding-icon">${icon('agents')}</div><div><h3>Your agent team starts here</h3><p>Connect a model, choose its tools, and assign its first task.</p></div>${button('Create your first agent', 'create-agent', 'plus', '', 'secondary')}</div>`}</section>`;
}

export function agents() {
  return `${heading('Agents', 'Configure and coordinate your AI agents.', button('Create agent', 'create-agent', 'plus', '', 'primary'), 'WORKSPACE / AGENTS')}<div class="section-toolbar"><div class="counter-label">All agents <span>${number(state.agents.length)}</span></div><span class="muted small">${number(state.agents.filter(a => a.enabled).length)} active · local execution</span></div>${state.agents.length ? `<div class="agent-grid">${state.agents.map(agentCard).join('')}</div>` : `<section class="panel big-empty">${empty('agents', 'Create your first agent', 'Name it, connect your Ollama model, and choose the tools it can use.', button('Create agent', 'create-agent', 'plus', '', 'primary'))}<div class="setup-steps"><span><b>01</b> Configure a model</span><span><b>02</b> Choose its tools</span><span><b>03</b> Assign a task</span></div></section>`}`;
}

export async function agentDetail(id) {
  const [agent, tasks, metrics] = await Promise.all([api(`/agents/${id}`), api(`/tasks?agent_id=${encodeURIComponent(id)}`), api(`/metrics?agent_id=${encodeURIComponent(id)}`)]);
  const current = agent.current_task ? await api(`/tasks/${agent.current_task.id}`) : null;
  const attrs = `data-id="${esc(id)}"`, allTabs = [['timeline', 'Execution Timeline'], ['metrics', 'Metrics'], ['logs', 'Logs'], ['tools', 'Tools'], ['configuration', 'Configuration'], ['history', 'Task History']];
  let content = '';
  if (state.tab === 'timeline') content = `<section class="panel">${panelHeading('Execution timeline', 'Actions and operational explanations. Private model reasoning is not shown.')}${current ? timeline(current.events || current.timeline) : tasks.length ? `<div class="panel-note">The agent has no active task. <a href="#/tasks/${esc(tasks[0].id)}">View its latest run ${icon('arrow')}</a></div>${timeline((await api(`/tasks/${tasks[0].id}`)).events)}` : empty('activity', 'The agent is ready', 'Assign a task to see its actions in real time.', button('Assign task', 'assign', 'play', attrs, 'primary'))}</section>`;
  else if (state.tab === 'metrics') content = metricsView(metrics, false);
  else if (state.tab === 'history') content = `<section class="panel">${panelHeading('Task history', 'Saved runs for this agent')}${taskTable(tasks)}</section>`;
  else if (state.tab === 'logs') content = `<section class="panel">${panelHeading('Agent logs', 'Latest 200 events', `<a class="text-link" href="#/logs?agent_id=${esc(id)}">Open filters ${icon('arrow')}</a>`)}${logTable(await api(`/logs?agent_id=${encodeURIComponent(id)}&limit=200`))}</section>`;
  else if (state.tab === 'tools') content = `<section class="panel">${panelHeading('Enabled tools', "The runtime enforces the agent's permissions and limits.", button('Configure tools', 'edit-agent', 'settings', attrs, 'secondary'))}<div class="tool-grid">${state.tools.map(tool => `<div class="tool-card ${agent.tools.includes(tool.name) ? 'enabled' : ''}"><div>${icon(tool.dangerous ? 'terminal' : 'tool')}<strong class="mono">${esc(tool.name)}</strong>${agent.tools.includes(tool.name) ? '<span class="badge success">Enabled</span>' : `<span class="subtle-tag">${tool.available ? 'Disabled' : 'Unavailable'}</span>`}</div><p>${esc(tool.description)}</p></div>`).join('')}</div></section>`;
  else content = `<section class="panel">${panelHeading('Agent configuration', 'Changes apply to future tasks.', button('Edit configuration', 'edit-agent', 'edit', attrs, 'secondary'))}<div class="config-view"><div class="key-values"><span>ID</span><code>${esc(agent.id)}</code><span>Role</span><span>${esc(agent.role || '—')}</span><span>Created</span><span>${date(agent.created_at, true)}</span>${Object.entries(agent.config).filter(([key]) => key !== 'system_prompt').map(([key, value]) => `<span>${esc(key)}</span><code>${esc(Array.isArray(value) ? value.join(', ') : value)}</code>`).join('')}</div><h3>System prompt</h3><pre>${esc(uiText(agent.config.system_prompt || 'No additional instructions'))}</pre></div></section>`;
  return `<a class="back-link" href="#/agents">${icon('back')} All agents</a>${heading(agent.name, agent.description || agent.role || 'General-purpose local agent', button('Configure', 'edit-agent', 'settings', attrs, 'secondary') + button('Assign task', 'assign', 'play', attrs, 'primary'), 'AGENT DETAIL')}<div class="agent-detail-summary"><div class="agent-detail-identity"><div class="avatar">${icon('agents')}</div><div>${badge(agent.status)}<span class="mono muted">${esc(agent.config.model)}</span></div></div><div class="agent-detail-controls">${button(agent.enabled ? 'Disable' : 'Enable', 'toggle-agent', '', `${attrs} data-enabled="${!agent.enabled}"`, 'small-button')}${button(agent.status === 'Paused' ? 'Resume' : 'Pause', agent.status === 'Paused' ? 'resume-agent' : 'pause-agent', agent.status === 'Paused' ? 'play' : 'pause', attrs, 'small-button')}${button('Restart', 'restart-agent', 'refresh', attrs, 'small-button')}${button('Duplicate', 'duplicate-agent', 'copy', attrs, 'small-button')}${button('Delete', 'delete-agent', 'trash', attrs, 'small-button danger-quiet')}</div></div><div class="current-task-card"><div><span class="eyebrow">CURRENT TASK</span><h3>${current ? `<a href="#/tasks/${esc(current.id)}">${esc(current.prompt)}</a>` : 'No task running'}</h3><p class="small muted">${current ? `${badge(current.status)} · ${duration(current.duration_seconds)} · ${number(current.tool_calls)} tool calls` : 'Assign a task whenever you want to start a new run.'}</p></div>${current ? `<div class="current-progress">${progress(current)}${button('Cancel task', 'cancel-task', 'stop', `data-id="${esc(current.id)}"`, 'small-button danger-quiet')}</div>` : ''}</div>${agent.status === 'Paused' ? '<div class="notice">Pausing takes effect between actions. An in-progress model or tool call may finish first.</div>' : ''}${tabs(allTabs, state.tab, 'agent-tab')}<div class="tab-content">${content}</div>`;
}

export async function tasks() {
  const filters = state.filters.tasks, items = await api(`/tasks?${query(filters)}`);
  return `${heading('Tasks', 'Every run, from start to result.', button('Assign task', 'assign', 'plus', '', 'primary'), 'WORKSPACE / TASKS')}<section class="panel"><div class="filter-bar"><div class="filter-label">${icon('filter')} Filter</div><select aria-label="Filter tasks by agent" data-filter="tasks" name="agent_id">${agentOptions(filters.agent_id)}</select><select aria-label="Filter tasks by status" data-filter="tasks" name="status"><option value="">All statuses</option>${['Queued', 'Running', 'Paused', 'Success', 'Failed', 'Cancelled'].map(value => `<option ${filters.status === value ? 'selected' : ''}>${value}</option>`).join('')}</select><span class="filter-count">${number(items.length)} tasks</span></div>${taskTable(items)}</section>`;
}

export async function taskDetail(id) {
  const task = await api(`/tasks/${id}`), attrs = `data-id="${esc(id)}"`;
  const actions = liveTask(task) ? button(task.status === 'Paused' ? 'Resume agent' : 'Pause agent', task.status === 'Paused' ? 'resume-agent' : 'pause-agent', task.status === 'Paused' ? 'play' : 'pause', `data-id="${esc(task.agent_id)}"`, 'secondary') + button('Cancel', 'cancel-task', 'stop', attrs, 'danger') : button('Run again', 'retry-task', 'refresh', attrs, 'primary');
  return `<a class="back-link" href="#/tasks">${icon('back')} Task history</a>${heading('Run details', task.id, actions, 'TASK EXECUTION')}<section class="panel task-overview"><div class="task-title-row"><h2>${esc(task.prompt)}</h2>${badge(task.status)}</div><div class="task-metadata"><span>${icon('agents')}<a href="#/agents/${esc(task.agent_id)}">${esc(task.agent_name)}</a></span><span>${icon('clock')}${date(task.started_at || task.created_at)}</span><span>${icon('cpu')}${esc(task.config.model)}</span></div>${progress(task)}<p class="small muted">The percentage shows the step budget used; it does not estimate the time remaining.</p><div class="task-stats"><div><span>Duration</span><strong>${duration(task.duration_seconds)}</strong></div><div><span>Steps</span><strong>${number(task.steps)}</strong></div><div><span>Tokens</span><strong>${compact(task.total_tokens)}</strong></div><div><span>Model / tools</span><strong>${number(task.model_calls)} / ${number(task.tool_calls)}</strong></div><div><span>Finished</span><strong class="small">${date(task.finished_at)}</strong></div></div><details data-detail="workspace-${esc(id)}" class="workspace-detail"><summary>${icon('folder')} Run workspace</summary><code>${esc(task.workspace)}</code></details></section>${task.status === 'Paused' ? '<div class="notice">Pause requested: the runtime waits between actions and keeps this run active.</div>' : ''}${task.error ? `<div class="error-banner">${icon('alert')}<div><strong>Run error</strong><p>${esc(uiText(task.error))}</p></div></div>` : ''}${task.result ? `<section class="panel task-result">${panelHeading('Result', 'Final response from the agent')}<pre>${esc(serialize(task.result))}</pre></section>` : ''}<section class="panel">${panelHeading('Execution Timeline', 'Persisted actions, tools, and results', `<span class="subtle-tag">${number((task.events || task.timeline || []).length)} events</span>`)}${timeline(task.events || task.timeline || [])}</section>`;
}

export async function logs() {
  const f = state.filters.logs, events = await api(`/logs?${query({ ...f, limit: 200 })}`);
  return `${heading('Logs', 'Explore the persistent record of every system action.', button('Refresh', 'refresh', 'refresh', '', 'secondary'), 'OBSERVABILITY / LOGS')}<section class="panel"><form class="log-filters" id="log-filters"><label>Agent<select name="agent_id" data-filter="logs">${agentOptions(f.agent_id)}</select></label><label>Task ID<input name="task_id" value="${esc(f.task_id || '')}" placeholder="Task ID" data-filter="logs"></label><label>Level<select name="level" data-filter="logs"><option value="">All levels</option>${['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'].map(v => `<option ${f.level === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label><label>Tool<select name="tool" data-filter="logs"><option value="">All tools</option>${state.tools.map(t => `<option ${f.tool === t.name ? 'selected' : ''}>${esc(t.name)}</option>`).join('')}</select></label><label>From<input type="datetime-local" name="date_from" value="${esc(f.date_from || '')}" data-filter="logs"></label><label>To<input type="datetime-local" name="date_to" value="${esc(f.date_to || '')}" data-filter="logs"></label><label class="checkbox-label"><input type="checkbox" name="error_only" data-filter="logs" ${f.error_only ? 'checked' : ''}>Errors only</label>${button('Clear filters', 'clear-logs', '', '', 'small-button')}</form><div class="log-list-meta"><span>${number(events.length)} events · max 200</span><span>${icon('shield')} Sensitive content is sanitized by the server</span></div><div class="log-table-header" aria-hidden="true"><span>Date and time</span><span>Level</span><span>Event / tool</span><span>Task</span><span></span></div>${logTable(events)}</section>`;
}

export function metricsView(m = {}, withHeading = true) {
  return `${withHeading ? heading('Metrics', 'Agent usage, performance, and results.', '<span class="subtle-tag">Live data · last 7 days</span>', 'OBSERVABILITY / METRICS') : ''}<div class="stats-grid">${stat('Tasks succeeded', number(m.successful_tasks), 'check', `${number(m.total_tasks)} total runs`)}${stat('Tasks failed', number(m.failed_tasks), 'alert', `${number(m.cancelled_tasks)} cancelled`)}${stat('Tokens used', compact(m.total_tokens), 'bolt', `${number(m.model_calls)} model calls`)}${stat('Average time', duration(m.avg_duration_seconds), 'clock', `${number(m.avg_steps)} steps per task`)}</div><div class="stats-grid secondary-stats">${stat('Tool calls', number(m.tool_calls), 'tool', 'Cumulative total')}${stat('Model calls', number(m.model_calls), 'cpu', 'Cumulative total')}${stat('Model response', duration(m.avg_model_seconds), 'activity', 'Average duration')}${stat('Running tasks', number(m.running_tasks), 'play', `${number(m.running_agents)} agents working`)}</div><section class="panel metrics-history">${panelHeading('Activity history', 'Daily values recorded by the runtime · UTC')}${chartTabs()}<div class="chart-body">${chart(m.history, state.chart, true)}</div></section><div class="two-column"><section class="panel">${panelHeading('Most-used tools', 'Total calls by tool')}${barChart(m.tools)}</section><section class="panel">${panelHeading('Errors by agent', 'Recorded error events')}${barChart(m.errors_by_agent, 'errors')}</section></div>`;
}

export function settings() {
  const config = state.config || {}, h = state.health || {};
  return `${heading('Settings', 'Infrastructure and workspace capability settings.', '', 'WORKSPACE / SETTINGS')}<div class="settings-grid"><section class="panel">${panelHeading('Local workspace', 'Running server configuration')}<div class="settings-rows"><div><span>${icon('database')} Persistence</span><strong>SQLite</strong></div><div><span>${icon('activity')} Live updates</span><strong>Server-Sent Events</strong></div><div><span>${icon('cpu')} Concurrent workers</span><strong>${number(h.runtime?.max_workers)}</strong></div><div><span>${icon('globe')} Model provider</span><strong>Ollama</strong></div><div><span>${icon('folder')} Persistent data</span><code>${esc(config.data_dir || '—')}</code></div><div><span>${icon('folder')} Automatic workspaces</span><code>${esc(config.workspaces_dir || '—')}</code></div></div><div class="panel-note">The model, its limits, and an optional workspace folder are configured per agent. Infrastructure settings are set when the server starts.</div></section><section class="panel">${panelHeading('Per-agent security', 'Explicit permissions and a limited scope')}<div class="security-items"><article>${icon('shield')}<div><h3>Controlled workspace root</h3><p>Reads and writes are limited to the selected folder and its allowed relative directories.</p></div></article><article>${icon('terminal')}<div><h3>Allowed tools</h3><p>Only enabled tools can run. Commands are checked against an allowlist.</p></div></article><article>${icon('logs')}<div><h3>Secrets stay out of configuration</h3><p>Set an environment variable name on the agent. Never enter secret values in prompts or forms.</p></div></article></div></section></div><section class="panel future-panel">${panelHeading('Platform capabilities', 'This version focuses on real local execution and monitoring.')}<div class="capabilities"><div><span>Local agents · Ollama</span><span class="badge success">Available</span></div><div><span>Local queue and concurrent execution</span><span class="badge success">Available</span></div><div><span>Persistent logs and metrics</span><span class="badge success">Available</span></div>${['Remote workers and containers', 'Automatic scheduling', 'Persistent memory and RAG', 'Agent teams and hierarchies', 'Web search, browser, and external connectors', 'Multi-user authentication'].map(label => `<div><span>${label}</span><span class="subtle-tag">Unavailable</span></div>`).join('')}</div></section>`;
}
